### ISSUE TITLE
Path not allowed when username is an e-mail

### ISSUE THREAD

**Issue by aakarsh-sasi** [johnno1962/InjectionIII#370]
Hi @johnno1962, 

Few of my fellow devs started facing this issue on a project we are working on. On debugging we found that it happens when your username is an email i.e has a special character. The error message in the debugger was helpful is finding this out! Just wanted to know why does injector fail in this case and if we can do something to solve it?
 
```
Could not locate compile command for /Users/xyz@gmail.com/Documents/Repo/MyProj/ViewController.swift.
This could be due to one of the following:
1. Injection does not work with Whole Module Optimization.
2. There are restrictions on characters allowed in paths.
3. File paths in the simulator are case sensitive.
Try a build clean then rebuild to make logs available or
consult: "/Users/xyz@gmail.com/Library/Developer/CoreSimulator/Devices/02365B5E-5412-4682-AA72-E2647D630F84/data/Containers/Data/Application/7BB1FEFF-A80A-4C99-BD15-91F06B82BC12/tmp/command.sh"
```

**Comment by johnno1962** [comment]
Hi, I'll look at that for you. seems like any parent directory of the project with an @ in the name could be causing the problem.

**Comment by aakarsh-sasi** [comment]
Yes that or the ".". Any workaround apart from creating new account?

**Comment by johnno1962** [comment]
I'll look at it in the next couple of days as it doesn't seem to be an easy fix for various reasons. There should be a new release coming up with new functionality soon.

**Comment by johnno1962** [comment]
It may be while before I make this new release, so if you're in a hurry, you can clone the project (with --recurse-submodules and change file InjectionIII/HotReloading/Sources/HotReloading/SwiftEval.swift, line 639 to:
```
                        elsif ($line =~ m{\#(regexp.escaping("\"$"))}oi and $line =~ " \#(arch)"\#(swiftpm)) {
```

**Comment by aakarsh-sasi** [comment]
Thanks a lot @johnno1962. We are using a script to download your latest release from GitHub releases and install it. It will get updated whenever you create the next release!

**Comment by aakarsh-sasi** [comment]
Will close the issue when release is available Does that work?

**Comment by johnno1962** [comment]
Sure, that's fine. I've released something new to the related HotReloading project and roll a new version of the app tomorrow.

**Comment by johnno1962** [comment]
I've published the binary release ahead of time:  https://github.com/johnno1962/InjectionIII/releases/tag/4.0.0RC1

Let me know if this doesn't fix the issue!

**Comment by aakarsh-sasi** [comment]
Will update you on Monday!

**Comment by aakarsh-sasi** [comment]
Hey, sorry for the delay @johnno1962 . So I checked it today using version 4.1.3 but it still fails with the same error

```
:syringe: :warning: Could not locate compile command for /Users/xyz@gmail.com/Desktop/MyProj/ViewController.swift
This could be due to one of the following:
1. Injection does not work with Whole Module Optimization.
2. There are restrictions on characters allowed in paths.
3. File paths in the simulator are case sensitive.
Try a build clean then rebuild to make logs available or
```

**Comment by aakarsh-sasi** [comment]
```
# search through build logs, most recent first
cd "/Users/xyz@gmail.com/Library/Developer/Xcode/DerivedData/MyProj-dqximnbwagqxsqeaiwkdmvtuwrhh/Logs/Build" &&
for log in `ls -t *.xcactivitylog`; do
    #echo "Scanning $log"
    /usr/bin/env perl "/Users/xyz@gmail.com/Library/Developer/CoreSimulator/Devices/C7B1560A-76AF-4999-A5DE-20FB4C8FC241/data/Containers/Data/Application/05C9D81C-13F2-4B54-AAC9-E2345CF264D5/tmp/eval101.pl" "$log" >"/Users/xyz@gmail.com/Library/Developer/CoreSimulator/Devices/C7B1560A-76AF-4999-A5DE-20FB4C8FC241/data/Containers/Data/Application/05C9D81C-13F2-4B54-AAC9-E2345CF264D5/tmp/eval101.sh" && exit 0
done
exit 1;

```

**Comment by johnno1962** [comment]
You may need to move the project out of the ~/Desktop folder as it has special permissions. The @ fix should be in the 4.1.3 version.

**Comment by aakarsh-sasi** [comment]
Hey, i have my project in Desktop and it seems to work for me. But not for the fellow dev who has email as username

**Comment by johnno1962** [comment]
Hi, What is the current error your colleague is getting?

**Comment by aakarsh-sasi** [comment]
> Hey, sorry for the delay @johnno1962 . So I checked it today using version 4.1.3 but it still fails with the same error. Tried clean build and rebuild. (Didn't try clearing derived data)
> 
> ```
> :syringe: :warning: Could not locate compile command for /Users/xyz@gmail.com/Desktop/MyProj/ViewController.swift
> This could be due to one of the following:
> 1. Injection does not work with Whole Module Optimization.
> 2. There are restrictions on characters allowed in paths.
> 3. File paths in the simulator are case sensitive.
> Try a build clean then rebuild to make logs available or
> consult: "/Users/xyz@gmail.com/Library/Developer/CoreSimulator/Devices/C7B1560A-76AF-4999-A5DE-20FB4C8FC241/data/Containers/Data/Application/05C9D81C-13F2-4B54-AAC9-E2345CF264D5/tmp/command.sh".
> ```

@johnno1962 this is the error in 4.1.3 too

**Comment by johnno1962** [comment]
Can you please tell him to move it out of the Desktop folder. This may work for you but can cause problems.

**Comment by aakarsh-sasi** [comment]
Sure, checking this. Which directory should the project be moved to so that this issue won't be in question?

**Comment by johnno1962** [comment]
Just not ~/Desktop or ~/Downloads as these directories have special significance for macOS in terms of permissions.

**Comment by aakarsh-sasi** [comment]
Hey, tried with 4.1.3 while having the project in Documents/. Still same error :/

**Comment by aakarsh-sasi** [comment]
Seems to work for non-email usernames in all the directories

**Comment by johnno1962** [comment]
Any directory other than ~/Documents or ~/Desktop please. With regards to the @ in the home directory problem can you $ bash ... run the script it mentions from the command line and you should see what the error is.

**Comment by johnno1962** [comment]
OK, I've review the code and found a second place that needs to be fixed when @ is used in the home directory (I was unable to test this as macOS doesn't even seem to allow this as you create an account.) Please try out this release https://github.com/johnno1962/InjectionIII/releases/tag/4.1.4 and let me know if it fixes the problem.

**Comment by aakarsh-sasi** [comment]
Hey, sorry couldn’t reply sooner. Will test and get back to you asap

**Comment by aakarsh-sasi** [comment]
Hey, still didn't work. Tried different directories including Documents Desktop and Downloads but no luck. Here is what is available on opening command.sh

```
# search through build logs, most recent first
cd "/Users/xyz@gmail.com/Library/Developer/Xcode/DerivedData/Zomato-dqximnbwagqxsqeaiwkdmvtuwrhh/Logs/Build" &&
for log in `ls -t *.xcactivitylog`; do
  #echo "Scanning $log"
  /usr/bin/env perl "/Users/xyz@gmail.com//Library/Developer/CoreSimulator/Devices/C7B1560A-76AF-4999-A5DE-20FB4C8FC241/data/Containers/Data/Application/2C2EED94-A256-4EBD-BD64-A3AC25C859D0/tmp/eval101.pl" "$log" >"/Users/xyz@gmail.com//Library/Developer/CoreSimulator/Devices/C7B1560A-76AF-4999-A5DE-20FB4C8FC241/data/Containers/Data/Application/2C2EED94-A256-4EBD-BD64-A3AC25C859D0/tmp/eval101.sh" && exit 0
done
exit 1;
```

**Comment by johnno1962** [comment]
Can you run the command.sh from the command line and tell me the output please?
```
$ bash /Users/xyz@gmail.com/Library/Developer/CoreSimulator/Devices/C7B1560A-76AF-4999-A5DE-20FB4C8FC241/data/Containers/Data/Application/05C9D81C-13F2-4B54-AAC9-E2345CF264D5/tmp/command.sh

**Comment by johnno1962** [comment]
Or paste/send me the perl file it mentions in the script: /Users/xyz@gmail.com//Library/Developer/CoreSimulator/Devices/C7B1560A-76AF-4999-A5DE-20FB4C8FC241/data/Containers/Data/Application/2C2EED94-A256-4EBD-BD64-A3AC25C859D0/tmp/eval101.pl

**Comment by johnno1962** [comment]
OK, another release https://github.com/johnno1962/InjectionIII/releases/tag/4.1.6. If you could give it a try perhaps we can get sort this out. The problem is InjectionIII uses perl to "grep" the build logs to find the command to recompile a file and @ is a special character like $ or \ It's been very tricky to get the escaping just right for this to work. If it doesn't work please run the command.sh file it mentions and send me the output (not the file itself) or send me the .pl perl script it mentions so I can see what there errors is. Cheers.

**Comment by aakarsh-sasi** [comment]
Worked in 4.1.6 😄 🎉

**Comment by aakarsh-sasi** [comment]
What did we change exactly?
